# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

The major difference between Vector and Matrix is that Vector is an One-dimensional Array and Matrix is a Two-Dimensional Array.

**2. How to import `NumPy` library?**

In [115]:
import numpy as np

In [119]:
np.__version__

'1.26.4'

**3. Convert the given Python list into NumPy array and check its data type**

In [16]:
list_1 = [1,2,3,4,5]

In [17]:
numpy_list = np.array(list_1)

In [120]:
type(numpy_list)

numpy.ndarray

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [123]:
array = np.arange(6)


In [124]:
array

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [127]:
zeros_array = np.zeros(5)

In [128]:
zeros_array

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [130]:
matrix = np.zeros((3,4))

In [32]:
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [35]:
ones_array = np.ones(5)

In [37]:
print(ones_array)

[1. 1. 1. 1. 1.]


**8. Generate an array of "5" tens.**

In [39]:
tens_array = np.ones(5) * 10

In [40]:
tens_array

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [45]:
even = np.arange(start=52, stop=100, step=2)

In [46]:
even

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [51]:
array = np.linspace(0, 1, 10)

step_size = array[1] - array[0]

In [50]:
print(array)
print(step_size)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
0.1111111111111111


**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [58]:
vect_array = np.arange(25)

In [62]:
vect_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
vectToMatrix = vect_array.reshape(5,5)

In [61]:
vectToMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
vect_array.shape = (5,5)

In [65]:
vect_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [72]:
pointVector = np.arange(start = 0.1, stop = 2.6, step = 0.1)
pointVectorToMatrix = pointVector.reshape(5,5)

In [73]:
pointVectorToMatrix

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [136]:
linSpaceArray = np.linspace(start = 0, stop = 24, num = 25, dtype = int)
linSpaceArray.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [138]:
print(linSpaceArray.reshape((5,5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**14. What is the main difference between `linspace()` and `arange()`?**

The main difference between linspace() and arange() is that linspace() generates a fixed number of evenly spaced values between a range, while arange() generates values with a specified step size

**15. How to generate a single random integer number using NumPy built-in function?**

In [140]:
random_integer = np.random.randint(10, 20)
print(random_integer)

11


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [ ]:
random_number_matrix = np.random.rand(7, 5)
random_number_matrix.reshape((7,5))

In [110]:
print(random_number_matrix)

[[0.1166549  0.18521902 0.71113806 0.77473117 0.54326835]
 [0.77945312 0.34066295 0.41717332 0.62309145 0.09964159]
 [0.24931496 0.28958121 0.96037959 0.56024431 0.5153702 ]
 [0.95447404 0.88435732 0.34995401 0.02032165 0.74858255]
 [0.74897452 0.61875555 0.37784119 0.26873483 0.33253469]
 [0.77504256 0.70987805 0.21111122 0.45977182 0.46837329]
 [0.68123144 0.16784578 0.05760575 0.50816258 0.90557309]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [111]:
identity_matrix = 5 * np.eye(5)

In [112]:
identity_matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])